### ISSUE TITLE
Random FFT fail 

### ISSUE THREAD

**Issue by interactiveaudiolab** [asdfang/HarmonizeMe#2]
First thing I sang to the website caused the FFT function in scipy to crash.

**Comment by asdfang** [comment]
Error log:

127.0.0.1 - - [24/Jun/2017 11:00:52] "GET /keyData HTTP/1.1" 200 -
<type 'numpy.ndarray'>
/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Here is your random progression in halfsteps away from melodic note: 
[[0, -6, -9], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, -9, -12], [0, -9, -12], [0, -8, -15], [0, -8, -15], [0, -8, -15], [0, -8, -15], [0, -7, -16]]
[2017-06-24 11:01:27,144] ERROR in app: Exception on /harmonizeData [POST]
Traceback (most recent call last):
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/asdfang/Desktop/YEAR3/17SPRING/399EECSindependentstudy/HarmonizeMe/flasktesting/examples/flask_test.py", line 43, in harmonizeData
    newdata = processAudioWithHarmonies(audiodata, tonic, mode)
  File "/Users/asdfang/Desktop/YEAR3/17SPRING/399EECSindependentstudy/HarmonizeMe/flasktesting/examples/flask_test.py", line 92, in processAudioWithHarmonies
    newaudio = harmonizeme(array, tonic, mode)
  File "/Users/asdfang/Desktop/YEAR3/17SPRING/399EECSindependentstudy/HarmonizeMe/flasktesting/examples/Harmonizer.py", line 246, in harmonizeme
    completedaudio, realized = harmonize(melodysd, tonic, audiospliced, mode)
  File "/Users/asdfang/Desktop/YEAR3/17SPRING/399EECSindependentstudy/HarmonizeMe/flasktesting/examples/Harmonizer.py", line 293, in harmonize
    npchord.append(librosa.effects.pitch_shift(melodynote, 44100, n_steps = prog_hs[ii][2]))
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/librosa/effects.py", line 274, in pitch_shift
    y_shift = core.resample(time_stretch(y, rate), float(sr) / rate, sr)
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/librosa/core/audio.py", line 287, in resample
    y_hat = scipy.signal.resample(y, n_samples, axis=-1)
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 1722, in resample
    X = fftpack.fft(x, axis=axis)
  File "/Users/asdfang/miniconda2/envs/HarmonizeMe/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 269, in fft
    "(%d) specified." % n)
ValueError: Invalid number of FFT data points (0) specified.
