### ISSUE TITLE
IF THE WEBSITE IS GETTING STUCK ANYWHERE (esp. on "Harmonizing now..." for more than 45-60 seconds):

### ISSUE THREAD

**Issue by asdfang** [asdfang/HarmonizeMe#22]
Google "my IP address" and tell me what your IP address was.
Tell me:
--date/time that you tried.
--what pages/buttons you clicked through. If you preserved your log on the web console, tell me too.
--how long you sang for (in seconds)
--did you make sure the url led with "https://" and it was in Chrome?
--are you on a phone or laptop

**Comment by asdfang** [comment]
error log:
2017-07-19 16:41:58,985: /home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
2017-07-19 16:41:58,999:   out=out, **kwargs)
2017-07-19 16:41:59,000: /home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
2017-07-19 16:41:59,000:   ret = ret.dtype.type(ret / rcount)
2017-07-19 18:35:14,821: IOError: write error
2017-07-19 18:35:14,854: Error running WSGI application
2017-07-19 18:35:14,871: GeneratorExit
2017-07-19 18:35:19,911: IOError: write error
2017-07-19 18:35:19,930: Error running WSGI application
2017-07-19 18:35:19,931: GeneratorExit

server log:
2017-07-19 18:35:09 *********************************
2017-07-19 18:35:09 User IP Address: 199.201.64.145
2017-07-19 18:35:14 keyData POST
2017-07-19 18:35:14 Wed Jul 19 18:35:14 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /keyData (ip 10.0.0.75) !!!
2017-07-19 18:35:14 Wed Jul 19 18:35:14 2017 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during POST /keyData (10.0.0.75)
2017-07-19 18:35:14 RuntimeError
2017-07-19 18:35:14 : 
2017-07-19 18:35:14 generator ignored GeneratorExit
2017-07-19 18:35:14 
2017-07-19 18:35:19 shiftData POST
2017-07-19 18:35:19 Wed Jul 19 18:35:19 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /shiftData (ip 10.0.0.75) !!!
2017-07-19 18:35:19 Wed Jul 19 18:35:19 2017 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during POST /shiftData (10.0.0.75)
2017-07-19 18:35:19 RuntimeError
2017-07-19 18:35:19 : 
2017-07-19 18:35:19 generator ignored GeneratorExit
2017-07-19 18:35:19 
2017-07-19 18:35:20 keyData GET

**Comment by asdfang** [comment]
another user's error:
*accidentally pressed "record" while it was in "harmonizing now...." and reloaded the page, then clicked harmonizing now. now it is stuck

error log:
2017-07-19 19:59:49,574: [2017-07-19 19:59:49,568] ERROR in app: Exception on /harmonizeData [POST]
2017-07-19 19:59:49,575: Traceback (most recent call last):
2017-07-19 19:59:49,575:   File "/home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2017-07-19 19:59:49,575:     response = self.full_dispatch_request()
2017-07-19 19:59:49,575:   File "/home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-07-19 19:59:49,575:     rv = self.handle_user_exception(e)
2017-07-19 19:59:49,575:   File "/home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-07-19 19:59:49,576:     reraise(exc_type, exc_value, tb)
2017-07-19 19:59:49,576:   File "/home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-07-19 19:59:49,576:     rv = self.dispatch_request()
2017-07-19 19:59:49,576:   File "/home/asdfang/HarmonizeMe/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2017-07-19 19:59:49,576:     return self.view_functions[rule.endpoint](**req.view_args)
2017-07-19 19:59:49,576:   File "/home/asdfang/gitfldr/HarmonizeMe/HarmonizeMeApp/flaskapp/flask_run.py", line 182, in harmonizeData
2017-07-19 19:59:49,577:     newdata = processAudioWithHarmonies(audiodata, tonic, mode, shift_data) #newdata is np.array
2017-07-19 19:59:49,577:   File "/home/asdfang/gitfldr/HarmonizeMe/HarmonizeMeApp/flaskapp/flask_run.py", line 427, in processAudioWithHarmonies
2017-07-19 19:59:49,577:     newaudio, pitchesmelody_verb, melody_midi, onset_times = harmonizeme(audio, tonic, mode, shift)
2017-07-19 19:59:49,577: ValueError: too many values to unpack

server log:
2017-07-19 19:56:34 *********************************
2017-07-19 19:56:34 User IP Address: 73.58.151.105
2017-07-19 19:56:37 keyData POST
2017-07-19 19:56:39 shiftData POST
2017-07-19 19:56:39 keyData GET
2017-07-19 19:56:53 upload_file POST
2017-07-19 19:56:55 length of original_audio_str first posted: 10909348
2017-07-19 19:56:56 originalAudio GET
2017-07-19 19:56:56 keyData GET
2017-07-19 19:56:57 length of original_audio_str gotten: 10909348
2017-07-19 19:57:26 harmonizedUploaded POST
2017-07-19 19:57:28 length of original_audio_str second posted: 10909350
2017-07-19 19:57:29 processAudioWithHarmonies called
2017-07-19 19:57:30 pitch and onset detection called
2017-07-19 19:57:30 pitch and onset detection done
2017-07-19 19:57:30 start pitch shifting
2017-07-19 19:57:36 end pitch shifting
2017-07-19 19:57:38 processAudioWithHarmonies end
2017-07-19 19:57:39 length of harmonized_audio_str first posted: 10952411
2017-07-19 19:57:44 keyData POST
2017-07-19 19:57:47 getAudios GET
2017-07-19 19:57:48 harmonized_audio_str length of string: 10952411
2017-07-19 19:57:48 original_audio_str length of string: 10909350
2017-07-19 19:57:48 harmonized_original_str length of string: 21861762
2017-07-19 19:58:57 keyData POST
2017-07-19 19:59:00 shiftData POST
2017-07-19 19:59:00 keyData GET
2017-07-19 19:59:47 harmonizeData POST
2017-07-19 19:59:48 length of original_audio_str first posted: 3379200
2017-07-19 19:59:48 processAudioWithHarmonies called
2017-07-19 19:59:48 pitch and onset detection called
2017-07-19 19:59:49 pitch and onset detection done
2017-07-19 20:02:40 keyData GET

**Comment by yangjerry110** [comment]
your set ip address is use for these softwore ,you can use "ps aux | grep  'your softwore name'" this command can see your softwore's ip address .
the first way:
you can kill your softwore,then restart your use softwore
the secend way:
you can set the other ip addree for your softwore use ip port,then restart your nginx
